version: '3'

services:
  php_apache_mysql:
    build:
      context: .
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - ./src:/var/www/html

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
